config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :droids do
    resources :rents, only: [:new, :create]
  end
  resources :rents, only: [:show, :destroy]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/droid.rb
class Droid < ApplicationRecord
  belongs_to :user
  has_many :rents, dependent: :destroy
  has_one_attached :photo
  validates :name, :category, :builder, :description, :era, :price_per_year, presence: true
  validates :name, uniqueness: true
  ERA = ['Old Republic', 'New Republic', 'Empire Sith' ]
  CATEGORY = ['Astomecano', 'Combat', 'Medical', 'Technicien', 'Utilitaire' ]
  BUILDER = ['Les mines de Dorvalla', 'Maison organa', 'République galactique', 'Résistance']

  def booked?(start_year, end_year, droid)
    droid.rents.each do |r|
      return false if (r.start_year..r.end_year).overlaps?(start_year..end_year)
    end
    # rents.where("start_year < ?", start_year).where("end_year > ?", start_year).first.present? || rents.where("start_year < ?", end_year).where("end_year > ?", end_year).first.present? || rents.where("start_year > ?", start_year).where("end_year < ?", end_year).first.present?
  end

  include PgSearch::Model
  multisearchable against: [:era, :category, :builder]

end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :droid
  validate :end_year_superior_to_start_year
  validate :year_rent_not_superior_500

  private

  def end_year_superior_to_start_year
    if end_year < start_year
      errors.add(:end_year, "can't be before start_year")
    end
  end

  def year_rent_not_superior_500
    if end_year - start_year > 500
      errors.add(:end_year, "can't be superior to 500")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  SPECIES = ['Yuzzum', 'Utapaun', 'Chagrian', 'Gand', 'Talz', 'Clawdites', 'Human', 'Kitonak']
  PLANET = ['Aargonar', 'Byss', 'Jabiim', 'Killun', 'Sebaddon', 'Stewjon', 'Wynkahthu', 'Zeffo']
  has_many :droids, dependent: :destroy
  has_many :rents, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :species, :planet, :radio_frequency, :photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :species, :planet, :radio_frequency, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    #devise_parameter_sanitizer.permit(:account_update, keys: :photo)
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/droids_controller.rb
class DroidsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :create]
  before_action :set_droid, only: [:show, :edit, :update, :destroy]

  def index
    # if params[:search]
    #   @era = params["search"]["era"]
    #   @category = params["search"]["category"]
    #   @builder = params["search"]["builder"]
    #   @droids.each do |droid|
    #     if droid.ear ==
    #   end
    # end
    @droids = Droid.all
    if params[:search].present?
      @droids = @droids.where(era: params[:search][:era]) if params[:search][:era].present?
      @droids = @droids.where(category: params[:search][:category]) if params[:search][:category].present?
      @droids = @droids.where(builder: params[:search][:builder]) if params[:search][:builder].present?
    end
    @droids = policy_scope(@droids)
  end

  def rented?
    true if !@droid.rents.first.nil?
  end

  def show
    # @droid = Droid.find(params[:id])
    authorize @droid
    @rent = Rent.new
    @rented = rented?
  end

  def edit
    # @droid = Droid.find(params[:id])
    authorize @droid
  end

  def update
    # @droid = Droid.find(params[:id])
    authorize @droid
    @droid.update(params_droid)
    @droid.user = current_user
    @droid.save

    redirect_to droids_path
  end

  def new
    @user = current_user
    @droid = Droid.new

    authorize @droid
  end

  def create
    @droid = Droid.new(params_droid)
    @user = current_user

    @droid.user = @user
    authorize @droid

    if @droid.save
      redirect_to droids_path
    else
      render :new
    end
  end

  def destroy
    # @droid = Droid.find(params[:id])
    authorize @droid
    @droid.destroy

    redirect_to droids_path
  end

  private

  def params_droid
    params.require(:droid).permit(:name, :category, :builder, :age, :description, :era, :price_per_year, :photo)
  end

  def set_droid
    @droid = Droid.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: []
  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_droid, only: [:new, :create, :overlaps]

  def show
    @rent = Rent.find(params[:id])
    authorize @rent
  end

  def new
    @rent = Rent.new
    authorize @rent
  end

  def create
    @rent = Rent.new(rent_params)
    authorize @rent
    @rent.droid = @droid
    @rent.user = current_user
    if @droid.booked?(@rent.start_year, @rent.end_year, @droid) && @rent.save
      # cas ou la date d'arrivée est après la date de départ + il n'est pas booké pour ces dates + on a réussi à sauvegarder le rent - il a passé ses validations
      redirect_to droid_path(@droid)
    elsif !@droid.booked?(@rent.start_year, @rent.end_year, @droid)
      flash[:alert] = "Droid already booked at these dates"
      render 'droids/show'
    else
      flash[:alert] = @rent.errors.full_messages.join(", ")
      render 'droids/show'
    end
  end

  def destroy
    @rent = Rent.find(params[:id])
    authorize @rent
    @rent.destroy

    redirect_to droid_path(@rent.droid_id)
  end

  private

  def rent_params
    params.require(:rent).permit(:start_year, :end_year)
  end

  def set_droid
    @droid = Droid.find(params[:droid_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def index
    @users = policy_scope(User)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/droids/edit.html.erb
<%= link_to 'Back', root_path %>

<div id="new-form">
  <%= simple_form_for(@droid) do |f| %>
      <%= f.input :name %>
      <%= f.input :category %>
      <%= f.input :builder %>
      <%= f.input :age %>
      <%= f.input :description %>
      <%= f.input :era %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
  <% end %>
  <%= f.submit "Modifier le droid", class: 'btn'%>
</div>

app/views/droids/index.html.erb
<div class="under-body">
  <%= simple_form_for :search, url: droids_path, method: "GET" do |f| %>
    <div class="search-bar d-flex flex-direction-row justify-content-between align-items-center">
      <div class="row w-100 content-box bg-white p-2">
        <div class="search-box-input px-2">
          <%= f.input :era, prompt: "ERA", label: false, collection: Droid::ERA %>
        </div>
        <div class="search-box-input px-2">
          <%= f.input :category, prompt: "CATEGORY", label: false, collection: Droid::CATEGORY %>
        </div>
        <div class="search-box-input px-2">
          <%= f.input :builder, prompt: "BUILDER", label: false, collection: Droid::BUILDER %>
        </div>
        <div class="search-box-submit px-2">
          <%= f.button :submit, 'Search 🔍' %>
        </div>
      </div>
    </div>
  <% end %>

  <%= render "shared/droid-card" %>
</div>

app/views/droids/new.html.erb
<div class="new-droid-content">
  <h1>Ajouter un nouveau droid à louer</h1>
  <div id="new-form">
    <%= simple_form_for (@droid) do |f| %>
    <%= f.input :name %>
    <%= f.input :category, collection: Droid::CATEGORY %>
    <%= f.input :builder, collection: Droid::BUILDER  %>
    <%= f.input :age %>
    <%= f.input :description %>
    <%= f.input :era, collection: Droid::ERA %>
    <%= f.input :price_per_year  %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Ajouter le droid", class: 'btn'%>
    <% end %>
  </div>

</div>

app/views/droids/show.html.erb
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.min.css">


<div class="card-droid">
  <div class="img-card">
    <% if @droid.photo.attached? %>
        <%= cl_image_tag @droid.photo.key %>
    <% else %>
      <img class="card-img-top" src="https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Card image cap">
    <% end %>
  </div>

  <div class="all-description">
    <div class="title-description">
      <h1><%= @droid.name %></h1>
      <div class="scroll">
        <p class="descr"><%= @droid.description %></p>
      </div>
    </div>

    <div class="midle">
        <div class="card-droid-infos">
          <div class="droid-info">
            <div class="lien">
              <ul>
                <li><i class="fas fa-user-astronaut"></i> <%= @droid.category %></li>
                <li><i class="fas fa-tools"></i>  <%= @droid.builder %></li>
                <li><i class="fas fa-cogs"></i>  <%= @droid.age %></li>
                <li><i class="fas fa-history"></i>  <%= @droid.era %></li>
              </ul>

              <% if @rented %>
                <div class="success">
                  <p><b>Last reservation</b></p>
                  <div id="des-name">
                  <p>Droid rented by <b> <%= @current_user.name %></b> : </p>
                    <% if @current_user.photo.attached? %>
                      <p><%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill %></p>
                    <% else %>
                    <% end %>
                    </div>
                  <p>From <b> <%= @droid.rents.last.start_year %></b> to <b><%= @droid.rents.last.end_year %></b></p>
                </div>
              <% else %>
              <% end  %>
            </div>
          </div>
        </div>

            <div class="joge">
              <div class="chose-date">
                <div id="jauge">
                 <p>Your price</p>
                 <hr>
                  <input id="ex1" data-price="<%= @droid.price_per_year %>" data-slider-id='ex1Slider' type="text" data-slider-min="0" data-slider-max="500" data-slider-step="1" data-slider-value="14"/>
                  <div id="year-div"><p id="years"><p><p>: years</p></div>
                </div>
                <div class="price">
                  <p><i class="fas fa-coins"></i></p><p id="calculprice"></p>
                </div>

                <div class="rent-btn">
                  <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal">
                    Rent this droid
                  </button>
                </div>
              </div>
            </div>
        </div>

            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Choose your dates</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= render "/rents/new", droid: @droid, rent: @rent %>
                </div>
              </div>
            </div>
          </div>

    <div class="footer-card">
      <div class="owner">
        <% if @droid.user.photo.attached? %>
          <%= link_to user_path(@droid.user) do %>
            <%= cl_image_tag @droid.user.photo.key, height: 40, width: 40, crop: :fill %>
          <% end %>
        <% end %>

        <%= link_to user_path(@droid.user) do %>
          <p>Louer le droid de <strong style="color: black"><%= @droid.user.name %></strong></p>
        <% end %>
      </div>

        <div class="btn-book-date">
          <% if current_user == @droid.user_id %>
            <%= link_to "Update", edit_droid_path(@droid) %>
            <%= link_to "Delete #{@droid.name}",
                        droid_path(@droid),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %>
          <% end %>
          <%= link_to 'Back', droids_path, class: 'btn-secondary' %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Air2D2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>


  <body>
    <% unless params[:action] == "home" %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= render 'shared/flashes' %>

    <p class="notice"><%= notice %></p>
    <div class="body_wrapper">
      <%= yield %>
    </div>

    <% unless params[:action] == "home" %>
      <%= render "shared/footer" %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
  <div class="home-content">
    <h5>May the Force Be With You</h5>
    <p id="p_margin_bottom">Rent the best Droid from all galaxies</p>
    <button id="btn-relou"><%= link_to "Light speed", droids_path %></button>
  </div>
</div>

app/views/rents/_new.html.erb
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Rent</h2>
    <%= simple_form_for [ @droid, @rent ] do |f| %>
      <%= f.input :start_year, collection: (2020..3000), required: false, input_html: {id: "range_start"} %>
      <%= f.input :end_year, collection: (2020..3000), required: false, input_html: {id: "range_end"} %>
    <div class="btn-ask-for-rent text-center">
      <%= f.button :submit, "Ask for rent", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/rents/new.html.erb
<div class="container-new-rent text-center">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Rent</h2>
    <%= simple_form_for [@droid, @rent] do |f| %>
      <%= f.input :start_year, collection: (2020..3000), required: false, input_html: {id: "range_start"} %>
      <%= f.input :end_year, collection: (2020..3000), required: false, input_html: {id: "range_end"} %>
    <div class="btn-ask-for-rent text-center">
      <%= f.button :submit, "Ask for rent", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>

app/views/rents/show.html.erb
<h1>This is a rent</h1>

<h4>The datetime:</h4>
<p><%= @rent.start_year %> /to/ <%= @rent.end_year %></p>

<h4>The droid:</h4>
<p><%= @rent.droid.name %></p>

<h4>The one who rent the droid:</h4>
<!-- this is a way to find who is the one that the droid belongs to -->
<p><%= @rent.droid.user.name %></p>

<h4>The one who pay</h4>
<p><%= @rent.user.name %></p>

app/views/shared/_droid-card.html.erb
<% if params[:controller] == "droids" %>

  <div class="all-cards">
    <% if @droids.empty? %>
      <p class="text-white">Sorry, no droids for <%= "#{params[:search][:category]}, #{params[:search][:era]}, and #{params[:search][:builder]}" %></p>
    <% end %>

    <% @droids.each do |droid| %>
      <div class="card mt-3 bg-light" style="width: 18rem;">
        <% if droid.photo.attached? %>
          <%= cl_image_tag droid.photo.key, height: 192, width: 288, crop: :fill, class:"card-img-top" %>
        <% else %>
          <img class="card-img-top" src="https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Card image cap">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= droid.name %></h5>
          <hr>
          <p class="card-text"><i class="fas fa-history"></i> <%= droid.era %></p>
          <p class="card-text"><i class="fas fa-user-astronaut"></i> <%= droid.category %></p>
          <p class="card-text"><i class="fas fa-tools"></i> <%= droid.builder %></p>
          <div class="price"><i class="fas fa-coins"></i> <%= droid.price_per_year %></div>
          <hr>
          <div class="card-button">
            <%= link_to "See more", droid_path(droid), class:"btn-see-more" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% else %>

   <div class="user-droids-recap">
    <h3><%= @user.name %>'s droids (<%= @user.droids.count %>)</h3>
    <div class="user-droids-content w-100">
      <div class="user-droids-wrap d-flex">
        <% @user.droids.each do |droid| %>
         <%= link_to droid_path(droid) do %>
          <% if droid.photo.attached? %>
            <div class="user-droid-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path droid.photo.key %>'); background-size: cover; background-position: center;">
          <% else %>
            <div class="user-droid-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'); background-size: cover; background-position: center;">
          <% end %>
              <div class="petite-bulle">
                <% if !droid.rents.first.nil? %>
                  <%= link_to droid_path(droid) do %>
                    <img src="https://www.flaticon.com/premium-icon/icons/svg/580/580670.svg" class="user-droid-rent-image">
                  <% end %>
                <% else %>
                  <%= link_to droid_path(droid) do %>
                    <img src="https://cdn0.iconfinder.com/data/icons/hotel-vacation/33/for_rent-512.png" class="user-droid-rent-image">
                  <% end %>
                <% end %>
              </div>
              <div class="user-droid-name"><p><%= droid.name %></p></div>
            </div>
         <% end %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.starwars.com/databank/jedi-order"><i class="fab fa-jedi-order"></i></a>
    <a href="https://www.starwars.com/databank/galactic-senate"><i class="fab fa-galactic-senate"></i></a>
    <a href="https://www.starwars.com/games-apps/star-wars-the-old-republic"><i class="fab fa-old-republic"></i></a>
    <a href="https://www.starwars.com/databank/galactic-republic"><i class="fab fa-galactic-republic"></i></a>
  </div>
  <div class="footer-copyright">
    The greatest teacher, failure is.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-robot"></i> <B>Air2D2</B>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to "Ajouter un droid", new_droid_path, class: "btn btn-primary" %>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item-home active">
          <%= link_to "Home",droids_path , class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "R2D2.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to "View profile", user_path(current_user), method: :get, class: "dropdown-item" %>
            <%= link_to "View all profils", users_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "se connecter", new_user_session_path, class: "nav-link" %>
          <%= link_to "s'inscrire",  new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_user-profile.html.erb
<div class="container-profile">
  <div class="container-profile-text">
    <div class="profile-text">
      <div class="text-user-profile">
        <h1><%= @user.name %></h1>
        <p><i class="fas fa-transgender-alt"></i> <%= @user.species %></p>
        <p><i class="fas fa-globe"></i> <%= @user.planet %></p>
        <p><i class="fas fa-broadcast-tower"></i> <%= @user.radio_frequency %></p>
        <p><i class="fas fa-envelope-square"></i> <%= @user.email %></p>
      </div>
    </div>
    <div class="photo-user-profile">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key %>
      <% else %>
        <img src="https://fr.web.img6.acsta.net/r_1280_720/newsv7/16/07/01/15/36/0448690.jpg" alt="Missa">
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user-rents.html.erb
<% if @user.rents.first.nil? %>
<% else %>
  <h3 class="fuckthistitle"><%= @user.name%>'s reservations</h3>
  <div class="container-rents">
    <% @user.rents.each do |rent| %>
        <div class="card-rent-droid">
          <div class="img-rent-droid">
            <% if rent.droid.photo.attached? %>
              <%= cl_image_tag rent.droid.photo.key, crop: :fill %>
            <% else %>
              <img class="card-img-top" src="https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Card image cap">
            <% end %>
          </div>
          <div class="card-rent-droid-infos">
            <h5 class="card-title"><%= rent.droid.name %></h5>
            <hr>
            <p class="card-rent-droid-text"><i class="fas fa-history"></i> <%= rent.droid.era %></p>
            <p class="card-rent-droid-text"><i class="fas fa-user-astronaut"></i> <%= rent.droid.category %></p>
            <p class="card-rent-droid-text"><i class="fas fa-tools"></i> <%= rent.droid.builder %></p>
          </div>
          <div class="card-rent-droid-button">
            <p class="price"><i class="fas fa-coins"></i> <%= rent.droid.price_per_year %></p>
            <%= link_to "See more", droid_path(rent.droid), class:"user-btn-see-more" %>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
 <div class="under-body">
  <div class="user-header">
    <h1 class="mr-3"> See profils </h1>
  </div>

  <div class="all-cards-users">
    <% @users.each do |user| %>
     <%= link_to user_path(user) do %>
        <div class="user-droid-card mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path user.photo.key %>'); background-size: cover; background-position: center;">
          <div class="user-droid-name"><p><%= user.name %></p></div>
        </div>
     <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header">
  <h1 class="mr-3"> <%= @user.name %>'s profile</h1>
</div>

<%= render "shared/user-profile" %>

<div class="user-list-all-droids" style="display: flex; flex-direction: column;">
  <%= render "shared/droid-card" %>
  <%= render "shared/user-rents" %>
</div>